### ISSUE TITLE
Missing includes?

### ISSUE THREAD

**Issue by ghost** [mikereidis/spirit2_free#1]
Sorry if this is a noob question, but I am trying to build this app, but am missing includes from jni/bt-hci.c :

```
#include "../../ul/jni/utils.c"
#include "../../ul/jni/acc_hci.c"
```

Where can they be found?

**Comment by mikereidis** [comment]
Hi, :)

The missing files can be found here:
http://forum.xda-developers.com/showpost.php?p=57970189&postcount=8793

Or attached.

Regards,
Mike.

**Comment by ghost** [comment]
Thanks, are the c files GPlv2 like the headers or AGPLv3 like this project? I want to include this ap in f-droid, a free/libre/open source app "store" and don't want to get them into trouble..

**Comment by mikereidis** [comment]
Take your pick. One of them says "...either version 2 of the License, or
(at your option) any later version." and I think this might be implied
anyway.

They are both unmodified files I grabbed from somewhere.

And header files are almost un-copyrightable anyway; it's mostly
definitions and the only "code" is simple one line inline functions that a
virtually just definitions.

**Comment by mikereidis** [comment]
If that doesn't alleviate your concerns, you could just say those 2 header
files are GPLv2, while the rest is AGPLv3.
