### ISSUE TITLE
Superuser request not in android manifest

### ISSUE THREAD

**Issue by sedrubal** [mikereidis/spirit2_free#2]
I get a message from my superuser app, that the superuser request permission isn't listed in the android manifest.

**Comment by mikereidis** [comment]
Chainfire declared that permission "deprecated", so I removed it: http://su.chainfire.eu/#updates-permission

But I have seen a red warning on CM12 Superuser, and some might configure it as required.

So it returns in the next release, probably soon.

Here's a case where the dev seems intent on the removal/deprecation: https://github.com/nelenkov/cryptfs-password-manager/issues/6

As long as having it is benign and makes sense, I'll keep it.

**Comment by sedrubal** [comment]
Mh ok. I use https://github.com/koush/Superuser on Android 4.4 and this App is complaining about. But it's working anyway...

**Comment by mikereidis** [comment]
I just updated the source. Check it.

**Comment by sedrubal** [comment]
wow thank you. :+1:  But I can't compile right now...

**Comment by mikereidis** [comment]
If it's a build bug in my code, let me know where.

**Comment by sedrubal** [comment]
Ah sorry, I can't try to build it, because I don't have the ndk and so on.

**Comment by mikereidis** [comment]
You could use the libraries that I built, but you need the SDK and ant of
course:
http://forum.xda-developers.com/attachment.php?attachmentid=3123735&d=1421711973
