### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by sedrubal** [mikereidis/spirit2_free#3]
I get the message "unsupported device error" on starting the app on nexus 5.

**Comment by mikereidis** [comment]
Google purposely disables FM unfixably in hardware on all Nexus devices after the original Nexus One (HTC Desire).

No software can fix that.

It IS possible to make fm SEEM to work on such devices, but the FM antenna pin(s) on the combo chip are shorted to ground, so there is no usable signal.

Nobody has even been able to re-enable FM as it requires reworking the PCB underneath an RF shield, with one exception: someone who reported to me about some unknown chinese device.

The majority of Android devices these days are similarly FM disabled, at least those sold in the "western world". It would require about 1 cent worth of tiny caps and coils to connect the FM antenna pin to the wired headset jack to enable the hardware.

This waste of hardware makes me sad, and will eventually kill Spirit as a sole income producer for myself. :(

Google, Apple, and US carriers all make higher profits when FM is disabled. Sprint however, gets millions of dollars every year from US FM broadcasters to support FM on their phones.

**Comment by sedrubal** [comment]
oh ok :(

Thank you for your reply.
